site_name: h-CNV Community
site_description: 'Website of the Human Copy Number Variation community'
site_author: Michael Baudis
copyright: '&copy; Copyright 2022 ELIXIR hCNV Members'
repo_name: 'hcnv.github.io'

repo_url: https://github.com/hCNV/hcnv.github.io
edit_uri: edit/main/docs/

###############################################################################

nav:
  - hCNV Home: index.md
  - About ELIXIR h-CNV: about.md
  - Contacts: contacts
  - h-CNV Projects: implementation-studies.md
  - Databases & Resources: resources
  - Genome Blog: "http://genome.blog"
  - h-CNV @ ELIXIR: 'https://elixir-europe.org/about-us/implementation-studies/2019-hcnv'
  - Beacon Project: 'https://beacon-project.io'

###############################################################################

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.saneheaders
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid   
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - mdx_gh_links:
      user: hCNV
      repo: hcnv.github.io
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

###############################################################################

theme:
  # name: readthedocs
  name: material
  palette:
    primary: deep orange
  favicon: img/site-logo-topright.png
  # logo: img/site-logo-topright.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
  custom_dir: mkdocs_overrides
      
plugins:
    - search
    # - with-pdf:
    #     author: Progenetix
    #     output_path: pdf/progenetix-documentation.pdf
    - macros
    # - mermaid2

extra:
  news:
    dir: news
    author: hCNV
    list_length: 50
    extended_preview: true
    excerpt_separator: <!--more-->
  contacts:
    dir: contacts
    author: hCNV
    list_length: 50
    extended_preview: true
    excerpt_separator: <!--more-->
  resources:
    dir: resources
    author: hCNV
    list_length: 50
    extended_preview: true
    excerpt_separator: <!--more-->
  social:
    # - icon: fontawesome/brands/twitter 
    #   link: https://twitter.com/progenetix
    - icon: fontawesome/brands/github 
      link: https://github.com/hCNV
extra_css:
  - css/theme_overrides.css
# extra_javascript:
  # - https://unpkg.com/mermaid/dist/mermaid.min.js
  # - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
    